name: Angular 6 Lint

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12  # You can change the Node.js version as needed

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint  # Modify this command to match your project setup

      - name: Run Stylelint
        run: npm run lint:styles  # Modify this command to match your project setup
